import uuid
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from signals import (
    classify_with_llm, classify_code_with_llm,
    compute_stylometric_score, compute_informality_score,
    compute_code_structure_score, aggregate_confidence,
)
import audit_log
import certificates
import analytics

load_dotenv()

app = Flask(__name__)
def _get_creator_id():
    body = request.get_json(silent=True) or {}
    return body.get("creator_id") or "anonymous"

limiter = Limiter(_get_creator_id, app=app, default_limits=[])

LABELS = {
    "ai_generated": (
        "This content shows strong indicators of AI generation. Our system analyzed "
        "the writing style and structure across multiple signals and found patterns "
        "consistent with AI-produced text."
    ),
    "human_authored": (
        "This content shows strong indicators of human authorship. Our system analyzed "
        "the writing style and structure across multiple signals and found patterns "
        "consistent with human-produced text."
    ),
    "uncertain": (
        "Our system was unable to confidently determine whether this content was written "
        "by a human or generated by AI. The signals we analyzed were either mixed or not "
        "strong enough to make a reliable attribution."
    ),
    "verified_human": (
        "This content has been verified as human-authored. The creator submitted a process "
        "statement describing their creative approach, which passed automated review. "
        "A provenance certificate has been issued for this content."
    ),
}

CONFIDENCE_THRESHOLD = 0.80
PROCESS_STATEMENT_MIN_LENGTH = 100
PROCESS_STATEMENT_HUMAN_THRESHOLD = 0.6
SUPPORTED_CONTENT_TYPES = ("text", "code")


def _label_for(classification: str, confidence: float) -> str:
    if confidence >= CONFIDENCE_THRESHOLD and classification in ("ai_generated", "human_authored"):
        return LABELS[classification]
    return LABELS["uncertain"]


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute")
def submit():
    body = request.get_json(silent=True)

    if not body:
        return jsonify({"error": "request body must be JSON"}), 422
    text = body.get("text")
    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "text is required and must be a non-empty string"}), 422
    if len(text.strip()) < 50:
        return jsonify({"error": "text must be at least 50 characters"}), 422
    if not body.get("creator_id"):
        return jsonify({"error": "creator_id is required"}), 422

    content_type = body.get("content_type", "text")
    if content_type not in SUPPORTED_CONTENT_TYPES:
        return jsonify({
            "error": f"content_type must be one of: {', '.join(SUPPORTED_CONTENT_TYPES)}"
        }), 422

    content_id = str(uuid.uuid4())
    creator_id = body["creator_id"]

    if content_type == "code":
        llm_score = classify_code_with_llm(text)
        signal_2_score = compute_code_structure_score(text)
        signal_3_score = compute_stylometric_score(text)
        signal_names = ("llm_score", "code_structure_score", "text_stylometric_score")
    else:
        llm_score = classify_with_llm(text)
        signal_2_score = compute_stylometric_score(text)
        signal_3_score = compute_informality_score(text)
        signal_names = ("llm_score", "stylometric_score", "informality_score")

    result = aggregate_confidence(llm_score, signal_2_score, signal_3_score)
    classification = result["classification"]
    confidence = result["confidence"]
    label = _label_for(classification, confidence)

    audit_log.append_entry({
        "content_id": content_id,
        "creator_id": creator_id,
        "content_type": content_type,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": classification,
        "confidence": confidence,
        signal_names[0]: round(llm_score, 2),
        signal_names[1]: round(signal_2_score, 2),
        signal_names[2]: round(signal_3_score, 2),
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "content_type": content_type,
        "classification": classification,
        "confidence": confidence,
        "label": label,
        "signals": {
            signal_names[0]: round(llm_score, 2),
            signal_names[1]: round(signal_2_score, 2),
            signal_names[2]: round(signal_3_score, 2),
        },
    }), 200


@app.route("/certify", methods=["POST"])
def certify():
    body = request.get_json(silent=True)

    if not body:
        return jsonify({"error": "request body must be JSON"}), 422

    content_id = body.get("content_id")
    creator_id = body.get("creator_id")
    process_statement = body.get("process_statement", "")

    if not content_id:
        return jsonify({"error": "content_id is required"}), 422
    if not creator_id:
        return jsonify({"error": "creator_id is required"}), 422
    if not process_statement or len(process_statement.strip()) < PROCESS_STATEMENT_MIN_LENGTH:
        return jsonify({
            "error": f"process_statement must be at least {PROCESS_STATEMENT_MIN_LENGTH} characters"
        }), 422

    entry = audit_log.find_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404
    if entry.get("creator_id") != creator_id:
        return jsonify({"error": "creator_id does not match the content's creator"}), 403
    if entry.get("attribution") != "human_authored":
        return jsonify({
            "error": "certification is only available for content classified as human_authored",
            "attribution": entry.get("attribution"),
        }), 422
    if entry.get("certificate_id"):
        return jsonify({
            "error": "a certificate has already been issued for this content",
            "certificate_id": entry["certificate_id"],
        }), 409

    # Verify the process statement itself reads as human-authored
    statement_score = classify_with_llm(process_statement.strip())
    if statement_score < PROCESS_STATEMENT_HUMAN_THRESHOLD:
        return jsonify({
            "error": (
                "your process statement did not pass verification — it reads as AI-generated. "
                "Please describe your creative process in your own words."
            ),
            "statement_score": round(statement_score, 2),
        }), 422

    certificate_id = certificates.issue_certificate({
        "content_id": content_id,
        "creator_id": creator_id,
        "process_statement": process_statement.strip(),
        "statement_score": round(statement_score, 2),
        "issued_at": datetime.now(timezone.utc).isoformat(),
    })

    audit_log.update_entry(content_id, {
        "certificate_id": certificate_id,
        "status": "verified_human",
    })

    return jsonify({
        "certificate_id": certificate_id,
        "content_id": content_id,
        "status": "verified_human",
        "label": LABELS["verified_human"],
        "issued_at": datetime.now(timezone.utc).isoformat(),
    }), 200


@app.route("/certificate/<certificate_id>", methods=["GET"])
def get_certificate(certificate_id):
    cert = certificates.find_by_id(certificate_id)
    if not cert:
        return jsonify({"error": "certificate not found"}), 404
    return jsonify(cert), 200


@app.route("/appeal/<content_id>", methods=["POST"])
def appeal(content_id):
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "request body must be JSON"}), 422

    creator_id = body.get("creator_id")
    reasoning = body.get("reasoning", "")

    if not creator_id:
        return jsonify({"error": "creator_id is required"}), 422
    if not reasoning or len(reasoning.strip()) < 20:
        return jsonify({"error": "reasoning must be at least 20 characters"}), 422

    entry = audit_log.find_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404
    if entry.get("creator_id") != creator_id:
        return jsonify({"error": "creator_id does not match the content's creator"}), 403
    if entry.get("status") == "under_review":
        return jsonify({"error": "an appeal is already pending for this content"}), 409

    audit_log.update_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": reasoning.strip(),
        "appeal_submitted_at": datetime.now(timezone.utc).isoformat(),
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been submitted and the content is now under review.",
    }), 200


@app.route("/analytics", methods=["GET"])
def get_analytics():
    return jsonify(analytics.get_summary()), 200


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": audit_log.get_entries()}), 200


if __name__ == "__main__":
    app.run(debug=True)
