import uuid
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from signals import classify_with_llm, compute_stylometric_score, aggregate_confidence
import audit_log

load_dotenv()

app = Flask(__name__)

LABELS = {
    "ai_generated": (
        "This content shows strong indicators of AI generation. Our system analyzed "
        "the writing style and structure across multiple signals and found patterns "
        "consistent with AI-produced text."
    ),
    "human_authored": (
        "This content shows strong indicators of human authorship. Our system analyzed "
        "the writing style and structure across multiple signals and found patterns "
        "consistent with human-produced text."
    ),
    "uncertain": (
        "Our system was unable to confidently determine whether this content was written "
        "by a human or generated by AI. The signals we analyzed were either mixed or not "
        "strong enough to make a reliable attribution."
    ),
}

CONFIDENCE_THRESHOLD = 0.80


def _label_for(classification: str, confidence: float) -> str:
    if confidence >= CONFIDENCE_THRESHOLD and classification in ("ai_generated", "human_authored"):
        return LABELS[classification]
    return LABELS["uncertain"]


@app.route("/submit", methods=["POST"])
def submit():
    body = request.get_json(silent=True)

    if not body:
        return jsonify({"error": "request body must be JSON"}), 422
    text = body.get("text")
    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "text is required and must be a non-empty string"}), 422
    if len(text.strip()) < 50:
        return jsonify({"error": "text must be at least 50 characters"}), 422
    if not body.get("creator_id"):
        return jsonify({"error": "creator_id is required"}), 422

    content_id = str(uuid.uuid4())
    creator_id = body["creator_id"]

    llm_score = classify_with_llm(text)
    stylometric_score = compute_stylometric_score(text)
    result = aggregate_confidence(llm_score, stylometric_score)

    classification = result["classification"]
    confidence = result["confidence"]
    label = _label_for(classification, confidence)

    audit_log.append_entry({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": classification,
        "confidence": confidence,
        "llm_score": round(llm_score, 2),
        "stylometric_score": round(stylometric_score, 2),
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "classification": classification,
        "confidence": confidence,
        "label": label,
        "signals": {
            "llm_score": round(llm_score, 2),
            "stylometric_score": round(stylometric_score, 2),
        },
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": audit_log.get_entries()}), 200


if __name__ == "__main__":
    app.run(debug=True)
