import math
import os
import re
from groq import Groq

_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


# ── Signal 1: LLM semantic classifier ────────────────────────────────────────

_SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by an AI language model.

AI-generated text tends to have: uniform sentence length, smooth transitions, formal vocabulary, filler phrases like "it is important to note" or "furthermore", comprehensive topic coverage with no gaps, no typos or informal phrasing, and a polished assistant-like tone.

Human-written text tends to have: varied sentence length, informal or idiosyncratic word choices, personal asides, incomplete thoughts, emotional register, typos or casual punctuation, and a voice that sounds like a specific person.

Examples:
- "Artificial intelligence represents a transformative paradigm shift. It is important to note that stakeholders must collaborate to ensure responsible deployment." → 0.0 (AI)
- "ok so i finally tried that ramen place and honestly? underwhelming. the broth was fine but WAY too salty" → 1.0 (human)
- "The meeting went well. We discussed quarterly results and outlined plans for the product launch." → 0.5 (uncertain)

Score the text and respond with ONLY a single decimal number — no explanation, no other text:
- 0.0 = almost certainly AI-generated
- 0.5 = genuinely uncertain
- 1.0 = almost certainly human-authored"""


def classify_with_llm(text: str) -> float:
    """
    Returns a score in [0.0, 1.0]: 0.0 = AI-generated, 1.0 = human-authored.
    Returns 0.5 (maximum uncertainty) if Groq is unreachable or returns unparseable output.
    """
    try:
        response = _get_client().chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            max_tokens=10,
        )
        raw = response.choices[0].message.content.strip()
        score = float(raw)
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


# ── Signal 2: Stylometric heuristics ─────────────────────────────────────────

def _split_sentences(text: str) -> list:
    return [s.strip() for s in re.split(r'(?<=[.!?])\s+', text.strip()) if s.strip()]


def _tokenize(text: str) -> list:
    return re.findall(r'\b\w+\b', text.lower())


def _sentence_length_variance_score(sentences: list) -> float:
    """High variance in sentence length → human-like (score near 1.0)."""
    lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    if len(lengths) < 2:
        return 0.5
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # std_dev of 15 words = score 1.0; below 5 words is very AI-like
    return min(std_dev / 15.0, 1.0)


def _avg_word_length_score(words: list) -> float:
    """Shorter average word length → human-like (score near 1.0).
    AI text favors longer, formal words; human text tends toward shorter ones.
    More length-invariant than TTR, which saturates on short texts.
    """
    if not words:
        return 0.5
    avg_len = sum(len(w) for w in words) / len(words)
    # avg_len 4 (short, conversational) → 1.0; avg_len 8 (long, formal) → 0.0
    return max(0.0, min(1.0, 1.0 - (avg_len - 4) / 4))


def _punctuation_density_score(text: str, words: list) -> float:
    """More expressive punctuation → human-like (score near 1.0)."""
    if not words:
        return 0.5
    expressive = len(re.findall(r'[!?;()]|—|\.\.\.', text))
    per_100 = (expressive / len(words)) * 100
    # 5 expressive marks per 100 words = score 1.0
    return min(per_100 / 5.0, 1.0)


def compute_stylometric_score(text: str) -> float:
    """
    Returns a score in [0.0, 1.0]: 0.0 = AI-like structure, 1.0 = human-like structure.
    Averages three sub-scores: sentence length variance, type-token ratio, punctuation density.
    Returns 0.5 if the text is too short to analyze reliably (< 2 sentences or < 10 words).
    """
    sentences = _split_sentences(text)
    words = _tokenize(text)

    if len(words) < 10 or len(sentences) < 2:
        return 0.5

    sentence_score = _sentence_length_variance_score(sentences)
    ttr_score = _avg_word_length_score(words)
    punct_score = _punctuation_density_score(text, words)

    return round((sentence_score + ttr_score + punct_score) / 3, 4)


# ── Signal 3: Informality / register ─────────────────────────────────────────

_CONTRACTIONS = re.compile(
    r"\b(can't|won't|don't|didn't|isn't|aren't|wasn't|weren't|"
    r"it's|that's|what's|there's|i'm|i've|i'd|i'll|"
    r"you're|you've|you'd|you'll|he's|she's|they're|we're|"
    r"could've|would've|should've|couldn't|wouldn't|shouldn't|"
    r"hasn't|haven't|hadn't|doesn't|let's)\b",
    re.IGNORECASE,
)
_FIRST_PERSON = re.compile(
    r"\b(i|me|my|mine|myself|we|our|ours|ourselves)\b",
    re.IGNORECASE,
)
_DISCOURSE = re.compile(
    r"\b(well|anyway|actually|honestly|literally|basically|totally|"
    r"i mean|kind of|sort of|you know|okay|ok|nah|yeah|yep|nope)\b",
    re.IGNORECASE,
)


def compute_informality_score(text: str) -> float:
    """
    Returns a score in [0.0, 1.0]: 0.0 = formal/AI-like, 1.0 = informal/human-like.
    Averages three sub-scores: contraction rate, first-person pronoun density,
    and informal discourse marker density.
    Returns 0.5 if the text is too short to analyze reliably (< 10 words).
    """
    words = _tokenize(text)
    if len(words) < 10:
        return 0.5

    per_100 = 100.0 / len(words)
    contraction_score = min(len(_CONTRACTIONS.findall(text)) * per_100 / 3.0, 1.0)
    first_person_score = min(len(_FIRST_PERSON.findall(text)) * per_100 / 5.0, 1.0)
    discourse_score = min(len(_DISCOURSE.findall(text)) * per_100 / 4.0, 1.0)

    return round((contraction_score + first_person_score + discourse_score) / 3, 4)


# ── Confidence aggregator ─────────────────────────────────────────────────────

def aggregate_confidence(llm_score: float, stylometric_score: float, informality_score: float) -> dict:
    """
    Combines three signal scores into a classification and confidence score.

    Classification: majority vote across three signals.
      - 2 or more signals strictly > 0.5 → human_authored
      - 2 or more signals strictly < 0.5 → ai_generated
      - Otherwise (split or ties at 0.5) → uncertain

    Confidence: weighted average (LLM 0.50, stylometric 0.30, informality 0.20),
    converted to distance from midpoint [0, 1].
    When uncertain, a penalty equal to the std dev of the three scores is applied
    to reflect how spread apart the signals are.
    """
    scores = [llm_score, stylometric_score, informality_score]
    votes_human = sum(1 for s in scores if s > 0.5)
    votes_ai = sum(1 for s in scores if s < 0.5)

    if votes_human >= 2:
        classification = "human_authored"
    elif votes_ai >= 2:
        classification = "ai_generated"
    else:
        classification = "uncertain"

    weighted_avg = 0.50 * llm_score + 0.30 * stylometric_score + 0.20 * informality_score
    raw_confidence = abs(weighted_avg - 0.5) * 2

    if classification == "uncertain":
        mean = sum(scores) / 3
        std_dev = math.sqrt(sum((s - mean) ** 2 for s in scores) / 3)
        raw_confidence = max(0.0, raw_confidence - std_dev)

    return {
        "classification": classification,
        "confidence": round(raw_confidence, 2),
    }
