import os
from groq import Groq

_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


_SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by an AI language model.

AI-generated text tends to have: uniform sentence length, smooth transitions, formal vocabulary, comprehensive coverage of a topic without gaps, no typos or informal phrasing, and a polished "assistant-like" tone.

Human-written text tends to have: varied sentence length, informal or idiosyncratic word choices, personal asides, incomplete thoughts, emotional register, typos or casual punctuation, and a voice that sounds like a specific person rather than a generic helpful assistant.

Score the text on this scale and respond with ONLY a single decimal number — no explanation, no other text:
- 0.0 = almost certainly AI-generated
- 0.5 = genuinely uncertain
- 1.0 = almost certainly human-authored"""


def classify_with_llm(text: str) -> float:
    """
    Returns a score in [0.0, 1.0]: 0.0 = AI-generated, 1.0 = human-authored.
    Returns 0.5 (maximum uncertainty) if Groq is unreachable or returns unparseable output.
    """
    try:
        response = _get_client().chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            max_tokens=10,
        )
        raw = response.choices[0].message.content.strip()
        score = float(raw)
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5
